name: inception

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

networks:
  inception-front:
    driver: bridge

  inception-back:
    driver: bridge
    internal: true 

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WORDPRESS_DATA_PATH}

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MARIADB_DATA_PATH}

  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${REDIS_DATA_PATH}

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt

  db_password:
    file: ../secrets/db_password.txt

  wp_admin_password:
    file: ../secrets/wp_admin_password.txt

  wp_password:
    file: ../secrets/wp_password.txt

  redis_password:
    file: ../secrets/redis_password.txt

  ftp_password:
    file: ../secrets/ftp_password.txt

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - NGINX_PORT

    image: nginx:inception_1
    container_name: inception_nginx

    volumes:
      - wordpress_data:/var/www/html

    networks:
      - inception-front
    ports:
      - "${NGINX_HOST_PORT}:${NGINX_PORT}"

    environment:
      - NGINX_HOST_PORT
      - NGINX_PORT
      - WORDPRESS_DATA_PATH
      - WORDPRESS_PORT
      - DOMAIN_NAME

    depends_on:
      wordpress:
        condition: service_healthy

    restart: unless-stopped
    logging: *default-logging

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile

    image: wordpress:inception_1
    container_name: inception_wordpress

    volumes:
      - wordpress_data:/var/www/html

    networks:
      - inception-front
      - inception-back

    environment:
      - WORDPRESS_DATA_PATH
      - WORDPRESS_PORT
      - MARIADB_HOST
      - MARIADB_PORT
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD_FILE=/run/secrets/db_password
      - DOMAIN_NAME
      - NGINX_HOST_PORT
      - WP_ADMIN_USER
      - WP_USER
      - WP_ADMIN_PASSWORD_FILE=/run/secrets/wp_admin_password
      - WP_PASSWORD_FILE=/run/secrets/wp_password
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
    secrets:
      - wp_admin_password
      - wp_password
      - db_password
      - redis_password

    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

    restart: unless-stopped
    logging: *default-logging

  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
      args:
        - MARIADB_PORT

    image: mariadb:inception_1
    container_name: inception_mariadb

    networks:
      - inception-back

    environment:
      - MARIADB_HOST
      - MARIADB_PORT
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_DATA_PATH
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MARIADB_PASSWORD_FILE=/run/secrets/db_password

    secrets:
      - db_root_password
      - db_password

    volumes:
      - mariadb_data:/var/lib/mysql

    restart: unless-stopped
    logging: *default-logging

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
      args:
        - REDIS_PORT

    image: redis:inception_1
    container_name: inception_redis

    networks:
      - inception-back

    environment:
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password

    secrets:
      - redis_password

    volumes:
      - redis_data:/data

    restart: unless-stopped
    logging: *default-logging

  pure-ftpd:
    build:
      context: ./pure-ftpd
      dockerfile: dockerfile
      args:
        - FTP_PORT

    image: pure-ftpd:inception_1
    container_name: inception_pureftpd

    volumes:
      - wordpress_data:/var/www/html

    networks:
      - inception-front

    ports:
      - "${FTP_PORT}:${FTP_PORT}"
      - "${FTP_PASSIVE_MIN_PORT}-${FTP_PASSIVE_MAX_PORT}:${FTP_PASSIVE_MIN_PORT}-${FTP_PASSIVE_MAX_PORT}"

    environment:
      - FTP_PORT
      - FTP_USER
      - FTP_PASSIVE_MIN_PORT
      - FTP_PASSIVE_MAX_PORT
      - DOMAIN_NAME

    secrets:
      - ftp_password

    depends_on:
      wordpress:
        condition: service_healthy

    restart: unless-stopped
    logging: *default-logging
