name: inception

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

networks:
  inception-front:
    driver: bridge

  inception-back:
    driver: bridge
    internal: true 

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WORDPRESS_DATA_PATH}

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MARIADB_DATA_PATH}

secrets:
  db_root_password:
    file: ./secrets/db_root_passwd.txt

  db_password:
    file: ./secrets/db_password.txt

  wp_admin_password:
    file: ./secrets/wp_admin_password.txt

  wp_password:
    file: ./secrets/wp_password.txt

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - NGINX_PORT

    image: ngninx:inception_1
    container_name: inception_ngninx

    volumes:
      - wordpress_data:/var/www/html

    networks:
      - inception-front
    ports:
      - "${NGINX_HOST_PORT}:${NGINX_PORT}"

    environment:
      - NGINX_HOST_PORT
      - NGINX_PORT
      - WORDPRESS_DATA_PATH
      - WORDPRESS_PORT
      - DOMAIN_NAME

    #depends_on:
    #  wordpress:
    #    condition: service_healthy

    restart: unless-stopped
    logging: *default-logging

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile

    image: wordpress:inception_1
    container_name: inception_wordpress

    volumes:
      - wordpress_data:/var/www/html

    networks:
      - inception-front
      - inception-back

    environment:
      - WORDPRESS_DATA_PATH
      - WORDPRESS_PORT

    secrets:
      - wp_admin_password
      - wp_wordpress
      - db_password

    depends_on:
      mariadb:
        condition: service_healthy

    restart: unless-stopped
    logging: *default-logging

  mariadb:
    build:
      context: ./mariaDB
      dockerfile: Dockerfile
      args:
        - MARIADB_PORT
    image: mariadb:inception_1
    container_name: inception_mariadb

    networks:
      - inception-back

    environment:
      - MARIADB_HOST
      - MARIADB_PORT
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_DATA_PATH
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MARIADB_PASSWORD_FILE=/run/secrets/db_password

    secrets:
      - db_root_password
      - db_password

    volumes:
      - mariadb_data:/var/lib/mysql

    restart: unless-stopped
    logging: *default-logging