user nginxuser;

worker_processes auto;

pid /run/nginx.pid;

events {
    worker_connections 1024;
}

include /etc/nginx/mime.types;
default_type application/octet-stream;

access_log /var/log/nginx/access.log;
error_log /var/log/nginx/error.log;

listen __NGINX_PORT__;
listen [::]:__NGINX_PORT__;

server_name __DOMAIN_NAME__;

absolute_redirect off;

root /var/www/html;
index index.php index.html index.htm;

location / {
    try_files $uri $uri/ /index.php?$args;
}

location ~ \.php$ {
    try_files $uri =404;
    fastcgi_pass wordpress:__WP_PORT__;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param HTTP_HOST $http_host;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
}

location ~ /\. {
    deny all;
}

