FROM alpine:3.20

RUN apk add --no-cache \
	mariadb mariadb-client

RUN mkdir -p /var/lib/mysql /run/mysqld && \
	chown -R mysql:mysql /var/lib/mysql /run/mysqld

COPY tools/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ARG MARIADB_PORT=3306
EXPOSE ${MARIADB_PORT}

HEALTHCHECK --interval=5s --timeout=3s --start-period=15s --retries=5 \
  CMD mariadb-admin ping --socket=/run/mysqld/mysqld.sock --silent || exit 1

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["mariadbd"]
