port __REDIS_PORT__
bind 0.0.0.0
protected-mode yes
requirepass __REDIS_PASSWORD__

dir /data
dbfilename dump.rdb
appendonly yes
appendfsync everysec

maxmemory 2gb
maxmemory-policy allkeys-lru

logfile ""