FROM alpine:3.20

RUN apk add --no-cache \
	nginx openssl wget libcap

COPY conf/nginx.conf /etc/nginx/nginx.conf

COPY tools/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ARG NGINX_PORT=443
EXPOSE ${NGINX_PORT}

HEALTHCHECK --interval=5s --timeout=3s --start-period=10s --retries=5 \
  CMD wget --no-verbose --tries=1 --spider https://localhost:${NGINX_PORT}/ || exit 1

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]