FROM alpine:3.20

RUN apk add --no-cache \
	php83 \
	php83-fpm \
	php83-phar \
	php83-mysqli \
	php83-curl \
	php83-gd \
	php83-intl \
	php83-mbstring \
	php83-xml \
	php83-zip \
	php83-opcache \
	php83-json \
	php83-session \
	php83-dom \
	php83-exif \
	php83-fileinfo \
	wget \
	mariadb-client \
	ca-certificates

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
	chmod +x wp-cli.phar && \
	mv wp-cli.phar /usr/local/bin/wp

WORKDIR /var/www/html

RUN mkdir -p /etc/php83/conf.d && \
    echo "memory_limit = 512M" > /etc/php83/conf.d/memory-limit.ini

COPY tools/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ARG WORDPRESS_PORT=9000
EXPOSE ${WORDPRESS_PORT}

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["php-fpm83", "-F"]